name: haruka
channels:
  - pytorch
  - nvidia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py311h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.12.31=h06a4308_0
  - certifi=2025.1.31=py311h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.8.55=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.8=3
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py311h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py311h5eee18b_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py311h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.5=py311h06a4308_0
  - jpeg=9e=h5eee18b_3
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.13.0.11=0
  - libcurand=10.3.9.55=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=hffd6297_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py311h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_2
  - mkl_fft=1.3.11=py311h5eee18b_0
  - mkl_random=1.2.8=py311ha02d727_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.4.2=py311h06a4308_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.15=h5eee18b_0
  - pillow=11.1.0=py311hcea889d_0
  - pip=25.0=py311h06a4308_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.11=he870216_0
  - pytorch=2.4.0=py3.11_cuda12.1_cudnn9.1.0_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py311h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py311h06a4308_1
  - setuptools=75.8.0=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.13.3=py311h06a4308_1
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.4.0=py311_cu121
  - torchtriton=3.0.0=py311
  - torchvision=0.19.0=py311_cu121
  - typing_extensions=4.12.2=py311h06a4308_0
  - wheel=0.45.1=py311h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.1.0
      - access==1.1.9
      - adjusttext==1.3.0
      - affine==2.4.0
      - aiobotocore==2.5.4
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.13
      - aioitertools==0.12.0
      - aiosignal==1.3.2
      - anndata==0.11.3
      - annotated-types==0.7.0
      - anyio==4.8.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - array-api-compat==1.10.0
      - arrow==1.3.0
      - asciitree==0.3.3
      - asttokens==3.0.0
      - async-lru==2.0.4
      - attrs==25.1.0
      - babel==2.17.0
      - beautifulsoup4==4.13.3
      - bleach==6.2.0
      - blitzgsea==1.3.50
      - botocore==1.31.17
      - cellcharter==0.3.3
      - cffi==1.17.1
      - chex==0.1.89
      - cinemaot==0.0.5
      - click==8.1.8
      - click-plugins==1.1.1
      - cligj==0.7.2
      - cloudpickle==3.1.1
      - clu==0.0.11
      - colorcet==3.1.0
      - comm==0.2.2
      - contourpy==1.3.1
      - cycler==0.12.1
      - dask==2024.12.1
      - dask-expr==1.1.21
      - dask-image==2024.5.3
      - datashader==0.17.0
      - debugpy==1.8.12
      - decorator==5.2.1
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - deprecation==2.1.0
      - distributed==2024.12.1
      - distro==1.9.0
      - dm-tree==0.1.9
      - docrep==0.3.2
      - einops==0.8.1
      - equinox==0.11.12
      - esda==2.7.0
      - et-xmlfile==2.0.0
      - etils==1.12.0
      - executing==2.2.0
      - fasteners==0.19
      - fastjsonschema==2.21.1
      - fiona==1.10.1
      - flax==0.8.5
      - fonttools==4.56.0
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2023.6.0
      - gast==0.6.0
      - geopandas==1.0.1
      - giddy==2.3.6
      - grpcio==1.70.0
      - gseapy==1.1.7
      - h11==0.14.0
      - h5py==3.13.0
      - harmonypy==0.0.10
      - hdf5plugin==5.1.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - humanize==4.12.1
      - igraph==0.11.8
      - imageio==2.37.0
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - inequality==1.1.1
      - inflect==7.5.0
      - ipykernel==6.29.5
      - ipython==8.32.0
      - isoduration==20.11.0
      - jax==0.5.1
      - jaxlib==0.5.1
      - jaxopt==0.8.3
      - jaxtyping==0.3.0
      - jedi==0.19.2
      - jiter==0.9.0
      - jmespath==1.0.1
      - joblib==1.4.2
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - kiwisolver==1.4.8
      - lamin-utils==0.13.11
      - lazy-loader==0.4
      - legacy-api-wrap==1.4.1
      - leidenalg==0.10.2
      - libpysal==4.13.0
      - lightning==2.5.0.post0
      - lightning-utilities==0.12.0
      - lineax==0.0.7
      - llvmlite==0.44.0
      - locket==1.0.0
      - mapclassify==2.8.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - matplotlib==3.8.4
      - matplotlib-inline==0.1.7
      - matplotlib-scalebar==0.9.0
      - matplotlib-venn==1.1.2
      - mdurl==0.1.2
      - mesa-py==0.1.2
      - mgwr==2.2.1
      - mistune==3.1.2
      - ml-collections==1.0.0
      - ml-dtypes==0.5.1
      - momepy==0.10.0
      - more-itertools==10.6.0
      - msgpack==1.1.0
      - mudata==0.3.1
      - multidict==6.1.0
      - multipledispatch==1.0.0
      - multiscale-spatial-image==1.0.1
      - muon==0.1.7
      - natsort==8.4.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.3.2
      - notebook-shim==0.2.4
      - numba==0.61.0
      - numcodecs==0.15.1
      - numpy==1.26.0
      - numpyro==0.17.0
      - ome-zarr==0.10.3
      - omnipath==1.0.8
      - openai==1.72.0
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optax==0.2.4
      - orbax-checkpoint==0.11.6
      - ott-jax==0.5.0
      - overrides==7.7.0
      - packaging==24.2
      - palettable==3.3.3
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - param==2.2.0
      - parso==0.8.4
      - partd==1.4.2
      - patsy==1.0.1
      - pexpect==4.9.0
      - pims==0.7
      - platformdirs==4.3.6
      - ply==3.11
      - pointpats==2.5.1
      - pooch==1.8.2
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - propcache==0.3.0
      - protobuf==5.29.3
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pubchempy==1.0.4
      - pulp==3.1.1
      - pure-eval==0.2.3
      - pyarrow==19.0.1
      - pycparser==2.22
      - pyct==0.5.0
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pydot==3.0.4
      - pygments==2.19.1
      - pygsp==0.5.1
      - pynndescent==0.5.13
      - pyogrio==0.10.0
      - pyomo==6.9.1
      - pyparsing==3.2.1
      - pyproj==3.7.1
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pysal==25.1
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.2.1
      - pytorch-lightning==2.5.0.post0
      - pytz==2025.1
      - pyzmq==26.2.1
      - quantecon==0.8.0
      - rasterio==1.4.3
      - rasterstats==0.20.0
      - referencing==0.36.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rpds-py==0.23.1
      - rtree==1.4.0
      - s3fs==2023.6.0
      - scanpy==1.11.0
      - scbsp==0.3.0
      - scenvi==0.3.7
      #- scenvi==0.4.1
      - scib==1.1.7
      - scikit-image==0.25.2
      - scikit-learn==1.5.2
      - scikit-misc==0.5.1
      - scipy==1.15.2
      #- scvi-tools==1.2.2.post2
      - seaborn==0.13.2
      - segregation==2.5.2
      - send2trash==1.8.3
      - session-info==1.0.0
      - session-info2==0.1.2
      - shapely==2.0.7
      - simplejson==3.20.1
      - six==1.17.0
      - sknw==0.15
      - slicerator==1.1.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - spaghetti==1.7.6
      - sparse==0.15.5
      - sparsecca==0.3.1
      - spatial-aging-clock==0.0.2
      - spatial-image==1.1.0
      - spatialdata==0.2.5.post0
      - spatialdata-plot==0.2.7
      - spglm==1.1.0
      - spint==1.0.7
      - splot==1.1.7
      - spopt==0.6.1
      - spreg==1.8.2
      - squidpy==1.6.2
      - stack-data==0.6.3
      - statsmodels==0.14.4
      - stdlib-list==0.11.1
      - tblib==3.0.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow-probability==0.22.1
      - tensorstore==0.1.72
      - terminado==0.18.1
      - texttable==1.7.0
      - threadpoolctl==3.5.0
      - tifffile==2025.2.18
      - tinycss2==1.4.0
      - tobler==0.12.1
      - toolz==1.0.0
      - torchgmm==0.1.2
      - torchmetrics==1.6.1
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typeguard==4.4.2
      - types-python-dateutil==2.9.0.20241206
      - typing-inspection==0.4.0
      - tzdata==2025.1
      - umap-learn==0.5.7
      - uri-template==1.3.0
      - urllib3==1.26.20
      - validators==0.34.0
      - wadler-lindig==0.1.4
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xarray==2024.7.0
      - xarray-dataclasses==1.9.1
      - xarray-datatree==0.0.15
      - xarray-schema==0.0.3
      - xarray-spatial==0.4.0
      - yarl==1.18.3
      - zarr==2.18.4
      - zict==3.0.0
      - zipp==3.21.0
prefix: /lab/solexa_sun/lab_members/yancui/miniconda3/envs/haruka
